name: Make a release with artifacts
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of just to make a release for"
        required: true
permissions:
  packages: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: download
        run: just download ${{ github.event.inputs.version }}
      - name: unzip
        run: just unzip ${{ github.event.inputs.version }}
      - name: repackage
        run: just repackage ${{ github.event.inputs.version }}
      - name: final
        run: just final ${{ github.event.inputs.version }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ github.event.inputs.version }}"
          draft: true
          files: |
            build/final/just-${{ github.event.inputs.version }}-aarch64-apple-darwin.tar.gz
            build/final/just-${{ github.event.inputs.version }}-aarch64-unknown-linux-musl.tar.gz
            build/final/just-${{ github.event.inputs.version }}-arm-unknown-linux-musleabihf.tar.gz
            build/final/just-${{ github.event.inputs.version }}-armv7-unknown-linux-musleabihf.tar.gz
            build/final/just-${{ github.event.inputs.version }}-x86_64-apple-darwin.tar.gz
            build/final/just-${{ github.event.inputs.version }}-x86_64-pc-windows-msvc.tar.gz
            build/final/just-${{ github.event.inputs.version }}-x86_64-unknown-linux-musl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
