name: Make a release with artifacts
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v2
      - name: download
        run: just download 1.26.0
      - name: unzip
        run: just unzip 1.26.0
      - name: repackage
        run: just repackage 1.26.0
      - name: final
        run: just final 1.26.0
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "1.26.0"
          draft: true
          files: |
            build/final/just-1.26.0-aarch64-apple-darwin.tar.gz
            build/final/just-1.26.0-aarch64-unknown-linux-musl.tar.gz
            build/final/just-1.26.0-arm-unknown-linux-musleabihf.tar.gz
            build/final/just-1.26.0-armv7-unknown-linux-musleabihf.tar.gz
            build/final/just-1.26.0-x86_64-apple-darwin.tar.gz
            build/final/just-1.26.0-x86_64-pc-windows-msvc.tar.gz
            build/final/just-1.26.0-x86_64-unknown-linux-musl.tar.gz
