name: Make a release with artifacts
on:
  push:
    tags:
      - "*"
permissions:
  packages: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: download
        run: just download ${{github.ref_name}}
      - name: unzip
        run: just unzip ${{github.ref_name}}
      - name: repackage
        run: just repackage ${{github.ref_name}}
      - name: final
        run: just final ${{github.ref_name}}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{github.ref_name}}"
          draft: true
          files: |
            build/final/just-${{github.ref_name}}-aarch64-apple-darwin.tar.gz
            build/final/just-${{github.ref_name}}-aarch64-unknown-linux-musl.tar.gz
            build/final/just-${{github.ref_name}}-arm-unknown-linux-musleabihf.tar.gz
            build/final/just-${{github.ref_name}}-armv7-unknown-linux-musleabihf.tar.gz
            build/final/just-${{github.ref_name}}-x86_64-apple-darwin.tar.gz
            build/final/just-${{github.ref_name}}-x86_64-pc-windows-msvc.tar.gz
            build/final/just-${{github.ref_name}}-x86_64-unknown-linux-musl.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
