name: Make a release with artifacts
on:
  push:
    tags:
      - *
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v2
      - name: test
        run: just download 1.26.0